services:
  - type: web
    name: edugen-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app -b 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_DISK_MOUNT_PATH
        value: /data
    disk:
      name: edugen-db-disk
      mountPath: /data
      sizeGB: 1
